export const CITIES: { slug: string; label: string }[] = [
  { slug: "bucuresti", label: "București" },
  { slug: "cluj-napoca", label: "Cluj-Napoca" },
  { slug: "timisoara", label: "Timișoara" },
  { slug: "iasi", label: "Iași" },
  { slug: "brasov", label: "Brașov" },
  { slug: "constanta", label: "Constanța" },
  { slug: "sibiu", label: "Sibiu" },
  { slug: "oradea", label: "Oradea" },
  { slug: "ploiesti", label: "Ploiești" },
  { slug: "arad", label: "Arad" },
  { slug: "pitesti", label: "Pitești" },
  { slug: "bacau", label: "Bacău" },
  { slug: "baia-mare", label: "Baia Mare" },
  { slug: "buzau", label: "Buzău" },
  { slug: "galati", label: "Galați" },
  { slug: "targu-mures", label: "Târgu-Mureș" },
  { slug: "suceava", label: "Suceava" },
];
