services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_olx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-olx-local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d my_olx"]
      interval: 5s
      timeout: 5s
      retries: 10

  localstack:
    image: localstack/localstack:3
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: eu-central-1
      LOCALSTACK_HOST: localstack
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
      - ./initaws:/etc/localstack/init/ready.d
      - ../../seed-data/images:/seed-images:ro
    networks:
      - my-olx-local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 20

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - my-olx-local
    restart: always

networks:
  my-olx-local:
    driver: bridge

volumes:
  postgres_data:
  localstack_data:
